### PR TITLE
Jenny index page

### PR DESCRIPTION
**Pull request by JRRFranklin**
Demo page basic form for James to play with

### CODE REVIEW

**Review by MThomas191 — CHANGES_REQUESTED** [review]
Testing a request for changes

conflicts exist, and I'm not sure what part you want to keep

**Comment by jameswillhoite** [comment]
It looks like you would want to get rid of master and keep your commits Jenny, but will let you make the changes.

**Comment by JRRFranklin** [comment]
I'm not quite sure how to do that. I just added a new file,  how can it have conflicts?

**Comment by JRRFranklin** [comment]
I see now. The conflicts were with the updates on the index page, not the demo page. I resolved them.

**Comment by JRRFranklin** [comment]
please squash and merge :)

**Review by MThomas191 — APPROVED** [review]

**Review by jameswillhoite — APPROVED** [review]

**Pull request merged**
